### ISSUE TITLE
Does not work with Voicepeak trial version on macOS 14 (have not tested paid version)

### ISSUE THREAD

**Issue by SnowySailor** [shinshin86/vpeak#2]
When I run `./vpeak -silent "こんにちは"` or `./vpeak -n f1 -e happy -o ./hello.wav "こんにちは"`, instead of generating the audio files, it opens a blank Voicepeak UI and it just hangs in my Terminal. I noticed that this also happens in Windows when I try to run the `voicepeak.exe` executable directly. Lastly, if I run the `voicepeak` command directly in the `.app` directory, I get the message `iconv_open is not supported` as well as another warning message below (maybe they changed something and this approach of calling the binary file will no longer work?). I have included screenshots of everything below.

Is this because I am using the trial version? If I bought the full version would everything work correctly? EDIT: I see it says `出力 (体験飯では利用できません)` in the menu, so that might be my problem. The menu is somewhat hidden at first so I didn't see it before creating this issue 😅 

<img width="238" alt="image" src="https://github.com/shinshin86/vpeak/assets/6320753/a304d9e4-5c47-4888-a7fe-33ea77a27452">

<img width="860" alt="image" src="https://github.com/shinshin86/vpeak/assets/6320753/06408e74-2dfa-4112-a795-30ee4df7ee21">

<img width="1283" alt="image" src="https://github.com/shinshin86/vpeak/assets/6320753/1e6a5092-3e76-4305-b154-bce0b3087b48">

I am running the latest version of the trial (I just downloaded it). I am also running a recent version of OSX (14.1.2) on an M1 Macbook Pro:
```
VOICEPEAK 1.0.1
© 2022 Dreamtonics 株式会社

== System Info ==
CPU:  0 MHz 10 Cores 10 Threads
CPU Features: 
Memory: 32768 MBytes
Operating System: Mac OSX 14.1.2 64 bits
User Language: en
User Region: US
Installation Path: /Applications/voicepeak.app/Contents/MacOS/voicepeak
Application Directory: [removed]

== Type Checks ==
sizeof(int) = 4
sizeof(long) = 8
sizeof(void*) = 8

Report generated at 16 Dec 2023 4:08.
Built on Apr 11 2022.
ダブルクリックでレポートをコピー
```

**Comment by shinshin86** [comment]
@SnowySailor Hello! Thanks for finding this project!

You might be right; the issue could be due to using the trial version.
For context, I am using the paid version.

By the way, do you have a file named `output.wav` in your current directory after you run this command?
At first, I assumed that this command outputs audio directly. However, I soon realized that it only outputs an audio file.
Assuming the process is successful, I was wondering if you actually have an output file in your case.

I also get the message `iconv_open is not supported` in my environment too.
I'm not sure of the cause, but since it hasn't affected the operation, I haven't investigated it further.

**Comment by SnowySailor** [comment]
Thanks for the fast reply! I was really happy to see a project like this cause I'm trying to automatically generate audio for my Japanese Anki deck and Voicepeak seems like the perfect tool for that. Are you also running the latest version of Voicepeak on macOS 14? If you are and everything is working, I might bite the bullet and pay for the full version and try that out.

> By the way, do you have a file named output.wav in your current directory after you run this command?

I do not see a .wav file generated. It looks like it just hangs and does nothing until I press ctrl-C. My guess is this is just related to it being the trial version. When you run your commands, does it open the Voicepeak application like mine does? Maybe that's just something the trial version does.

**Comment by shinshin86** [comment]
@SnowySailor I'm currently using macOS version 13.
Before making a purchase, it might be a good idea to check out feedback on social media platforms to ensure it's safe to upgrade.
This could influence your decision to buy it.

Regarding VOICEPEAK, I'm using version 1.2.6 because I've found that the dictionary function sometimes doesn't work properly with the latest version.
However, if you don't rely on the dictionary function, the latest version should be fine for you.
I'm not certain where to find older versions for download, so it's best to reach out to support directly with any specific inquiries.

Thank you for your reply on the `output.wav` about.
In my experience, using the `vpeak` command doesn't actually open the VOICEPEAK application.
You are right, It appears this issue may be linked to the software being a trial version.

**Comment by SnowySailor** [comment]
Issue is likely a result of using the trial version. It doesn't seem like anything is broken.

**Comment by SnowySailor** [comment]
Just a note, I emailed the company and asked about command line usage and their reply was just
> 体験版・製品版問わず、
弊社製品ではコマンドライン（CL）は非対応です。

So I guess it's not an officially supported feature, which means they could remove it at any time. That seems kind of strange because it would be a very useful feature to officially support... They already did the work to make it support command line arguments (as this repo demonstrates) so why not make it official 🙄

**Comment by mochi-co** [comment]
Hi @shinshin86, @SnowySailor - I am an experiencing the same problem. I was wondering if either of you could confirm that the current version of VoicePeak (paid) works with command line on MacOS? Thank you :)

**Comment by shinshin86** [comment]
@mochi-co 
Thank you for your question!  
I tested the latest version of VOICEPEAK (`VOICEPEAK 1.2.14`), and it worked without any issues.  
The environment I tested on was an M2 MacBook Air running macOS `13.7.2`.

**Comment by shinshin86** [comment]
@SnowySailor 
Sorry for the delayed response.

I completely agree with you—it does seem quite strange.
If CLI support were made official, it would be an incredibly useful update for users who want to integrate VOICEPEAK into various programs.

**Comment by SnowySailor** [comment]
@mochi-co I also use the paid version and it works well enough for my needs. However you are limited to 140 characters via the CLI even with the paid version (even though it's unlimited in the UI). I haven't found a way around that unfortunately.

**Comment by mochi-co** [comment]
@shinshin86 @SnowySailor Thank you very much, I will look into it further then :)

**Comment by shinshin86** [comment]
@SnowySailor @mochi-co 
Yes, it is true that the CLI appears unable to handle a large number of characters at once.

When I use the CLI to create a process for generating a large amount of audio, I typically split the text into smaller segments and process them multiple times.

Of course, this may vary depending on the case, but I hope this serves as a helpful reference!

**Comment by SnowySailor** [comment]
Maybe if enough people email them requesting that the CLI be allowed to process more than 140 characters they'll remove that limit :) 

Either that or they will disable it entirely...
